import 'package:equatable/equatable.dart';
import 'package:iv_project_model/src/converters/date_time_converter.dart';
import 'package:iv_project_model/src/enums/midtrans_transaction_status_type.dart';
import 'package:iv_project_model/src/enums/payment_method_type.dart';
import 'package:iv_project_model/src/enums/product_type.dart';
import 'package:iv_project_model/src/enums/transaction_status_type.dart';

class const TransactionResponse({
  required final String id,
  required final String transactionCode,
  required final ProductType productType,
  required final String productName,
  required final String productId,
  required final String productDescription,
  required final TransactionStatusType status,
  required final PaymentMethodType paymentMethod,
  required final String referenceNumber,
  required final String paymentURL,
  required final String acquirer,
  required final MidtransTransactionStatusType midtransStatus,
  final DateTime? timeLimitAt,
  required final int idrPrice,
  required final int idrDiscount,
  required final int idrTotalPrice,
  required final int ivcPrice,
  required final int ivcDiscount,
  required final int ivcTotalPrice,
  required final int voucherCodeId,
  required final String voucherCodeName,
  required final int idrVoucherCodeDiscount,
  required final int ivcVoucherCodeDiscount,
  required final String paymentProofImageUrl,
  required final DateTime createdAt,
  required final DateTime updatedAt,
}) extends Equatable {
  factory fromJson(Map<String, dynamic> json) {
    return .new(
      id: json['id'],
      transactionCode: json['transaction_code'],
      productType: ProductTypeExtension.fromJson(json['product_type']),
      productName: json['product_name'],
      productId: json['product_id'],
      productDescription: json['product_description'],
      status: TransactionStatusTypeExtension.fromJson(json['status']),
      paymentMethod: PaymentMethodTypeExtension.fromJson(json['payment_method']),
      referenceNumber: json['reference_number'],
      paymentURL: json['payment_url'],
      acquirer: json['acquirer'],
      midtransStatus: MidtransTransactionStatusTypeExtension.fromJson(json['midtrans_status']),
      timeLimitAt: DateTimeConverter.fromJson(json['time_limit_at'] ?? ''),
      idrPrice: json['idr_price'],
      idrDiscount: json['idr_discount'],
      idrTotalPrice: json['idr_total_price'],
      ivcPrice: json['ivc_price'],
      ivcDiscount: json['ivc_discount'],
      ivcTotalPrice: json['ivc_total_price'],
      voucherCodeId: json['voucher_code_id'],
      voucherCodeName: json['voucher_code_name'],
      idrVoucherCodeDiscount: json['idr_voucher_code_discount'],
      ivcVoucherCodeDiscount: json['ivc_voucher_code_discount'],
      paymentProofImageUrl: json['payment_proof_image_url'],
      createdAt: DateTimeConverter.fromJson(json['created_at'])!,
      updatedAt: DateTimeConverter.fromJson(json['updated_at'])!,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'transaction_code': transactionCode,
      'product_type': productType.toJson(),
      'product_name': productName,
      'product_id': productId,
      'product_description': productDescription,
      'status': status.toJson(),
      'payment_method': paymentMethod.toJson(),
      'reference_number': referenceNumber,
      'payment_url': paymentURL,
      'acquirer': acquirer,
      'midtrans_status': midtransStatus.toJson(),
      'time_limit_at': DateTimeConverter.toJson(createdAt),
      'idr_price': idrPrice,
      'idr_discount': idrDiscount,
      'idr_total_price': idrTotalPrice,
      'ivc_price': ivcPrice,
      'ivc_discount': ivcDiscount,
      'ivc_total_price': ivcTotalPrice,
      'voucher_code_id': voucherCodeId,
      'voucher_code_name': voucherCodeName,
      'idr_voucher_code_discount': idrVoucherCodeDiscount,
      'ivc_voucher_code_discount': ivcVoucherCodeDiscount,
      'payment_proof_image_url': paymentProofImageUrl,
      'created_at': DateTimeConverter.toJson(createdAt),
      'updated_at': DateTimeConverter.toJson(updatedAt),
    };
  }

  @override
  List<Object?> get props => [
    id,
    transactionCode,
    productType,
    productName,
    productId,
    productDescription,
    status,
    paymentMethod,
    referenceNumber,
    paymentURL,
    acquirer,
    midtransStatus,
    timeLimitAt,
    idrPrice,
    idrDiscount,
    idrTotalPrice,
    ivcPrice,
    ivcDiscount,
    ivcTotalPrice,
    voucherCodeId,
    voucherCodeName,
    idrVoucherCodeDiscount,
    ivcVoucherCodeDiscount,
    paymentProofImageUrl,
    createdAt,
    updatedAt,
  ];
}
